// Mocks generated by Mockito 5.4.6 from annotations
// in my_logger_metrics/test/my_logger_metrics_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:my_logger_metrics/src/config/app_config.dart' as _i2;
import 'package:my_logger_metrics/src/logger/app_logger.dart' as _i3;
import 'package:my_logger_metrics/src/metrics/app_metrics.dart' as _i4;
import 'package:my_logger_metrics/src/metrics/aptabase_metrics_client.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppConfig_0 extends _i1.SmartFake implements _i2.AppConfig {
  _FakeAppConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i3.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeAppConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.AppConfig);

  @override
  void d(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#d, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void i(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#i, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void w(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#w, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void e(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#e, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppMetrics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppMetrics extends _i1.Mock implements _i4.AppMetrics {
  MockAppMetrics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> trackEvent(
    String? eventName, [
    Map<String, dynamic>? props,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [eventName, props]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> Function([Map<String, dynamic>?]) timeEvent(
    String? eventName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#timeEvent, [eventName]),
            returnValue: ([Map<String, dynamic>? props]) =>
                _i5.Future<void>.value(),
          )
          as _i5.Future<void> Function([Map<String, dynamic>?]));
}

/// A class which mocks [AptabaseMetricsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAptabaseMetricsClient extends _i1.Mock
    implements _i6.AptabaseMetricsClient {
  MockAptabaseMetricsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get appKey =>
      (super.noSuchMethod(
            Invocation.getter(#appKey),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appKey),
            ),
          )
          as String);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackEvent(
    String? eventName, [
    Map<String, dynamic>? props,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [eventName, props]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
